version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    cooldown:
      default-days: 7
      semver-major-days: 7
      semver-minor-days: 7
      semver-patch-days: 7
    groups:
      npm-minor-patch-updates:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
